name: rta
channels:
  - defaults
dependencies:
  - pip=22.3
  - python=3.10
  - jupyter=1
  - notebook=6
  - pandas=1.5
  - numpy-base=1.23.5
  - scikit-learn=1.2
  - matplotlib
  - seaborn=0.12
  - pip:
      - kaggle==1.5.12
      - numpy==1.24.1
